version: '2'
services:
 
  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
       
  web:
    container_name: web
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - /usr/src/app/static
    env_file: .env
    command: gunicorn -w 2 -b :8000 server:app
  
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  bot:
    restart: on-failure
    build: ./bot
    env_file: .env
    links:
      - postgres:postgres
    command: python3 run.py
